# Generated by Django 4.2.6 on 2023-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_review_winery_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
