# Generated by Django 4.2.6 on 2023-12-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="winery",
            name="reviews",
        ),
        migrations.AddField(
            model_name="review",
            name="winery",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="app.winery",
            ),
            preserve_default=False,
        ),
    ]
